import { matchBoxFromStatic, type MatchBoxScore } from "./match-box-score";

/** Demo fixture: SPU 67 – 88 BAN (IYBC-style). Quarters sum to final. */
export const spuBanFixture: MatchBoxScore = matchBoxFromStatic({
  meta: {
    tournament: "Basketball Thai League 2026",
    date: "Sat 04 Jul 2026",
    tipOff: "12:00",
    venue: "สนามบาสเกตบอลไฮเทค",
    gameNo: "5205949",
    homeCode: "SPU",
    awayCode: "BAN",
    homeName: "สโมสรบาสเกตบอลมหาวิทยาลัยศรีปทุม",
    awayName: "Banvas Slammers TNS - TST",
    finalHome: 67,
    finalAway: 88,
  },
  byQuarter: [
    { period: 1, home: 14, away: 9 },
    { period: 2, home: 18, away: 26 },
    { period: 3, home: 14, away: 20 },
    { period: 4, home: 21, away: 33 },
  ],
  home: {
    teamId: "team-spu",
    code: "SPU",
    name: "สโมสรบาสเกตบอลมหาวิทยาลัยศรีปทุม",
    players: [
      {
        playerId: "p0",
        no: "0",
        name: "Vaughn Donald Chester",
        min: "37:17",
        fg2: { made: 3, att: 8 },
        fg3: { made: 1, att: 4 },
        ft: { made: 3, att: 4 },
        reb: { off: 0, def: 9, tot: 9 },
        ast: 2,
        to: 1,
        st: 5,
        blk: 3,
        pf: 2,
        pts: 12,
      },
      {
        playerId: "p23",
        no: "23",
        name: "ศุภกร แซ่หมิง (C)",
        min: "33:00",
        fg2: { made: 4, att: 11 },
        fg3: { made: 2, att: 7 },
        ft: { made: 2, att: 2 },
        reb: { off: 4, def: 3, tot: 7 },
        ast: 3,
        to: 3,
        st: 1,
        blk: 0,
        pf: 2,
        pts: 16,
      },
      {
        playerId: "p24",
        no: "24",
        name: "Don Wayde Basadre",
        min: "36:39",
        fg2: { made: 6, att: 13 },
        fg3: { made: 2, att: 9 },
        ft: { made: 2, att: 2 },
        reb: { off: 4, def: 3, tot: 7 },
        ast: 7,
        to: 6,
        st: 3,
        blk: 0,
        pf: 2,
        pts: 20,
      },
    ],
    teamTotals: {
      fg2: { made: 13, att: 32 },
      fg3: { made: 5, att: 20 },
      ft: { made: 7, att: 8 },
      reb: { off: 18, def: 29, tot: 47 },
      ast: 17,
      to: 26,
      st: 17,
      blk: 5,
      pf: 22,
      pts: 67,
    },
  },
  away: {
    teamId: "team-ban",
    code: "BAN",
    name: "Banvas Slammers TNS - TST",
    players: [
      {
        playerId: "p2",
        no: "2",
        name: "Nyang Wek",
        min: "38:05",
        fg2: { made: 8, att: 20 },
        fg3: { made: 0, att: 0 },
        ft: { made: 6, att: 12 },
        reb: { off: 10, def: 10, tot: 20 },
        ast: 6,
        to: 4,
        st: 4,
        blk: 2,
        pf: 2,
        pts: 22,
      },
      {
        playerId: "p10",
        no: "10",
        name: "ศุภกฤต ฐิติคุณรัตน์",
        min: "30:13",
        fg2: { made: 1, att: 3 },
        fg3: { made: 5, att: 7 },
        ft: { made: 3, att: 3 },
        reb: { off: 0, def: 2, tot: 2 },
        ast: 3,
        to: 3,
        st: 3,
        blk: 0,
        pf: 1,
        pts: 20,
      },
      {
        playerId: "p18",
        no: "18",
        name: "Kareem Jackson",
        min: "27:53",
        fg2: { made: 8, att: 14 },
        fg3: { made: 1, att: 1 },
        ft: { made: 2, att: 4 },
        reb: { off: 6, def: 6, tot: 12 },
        ast: 2,
        to: 2,
        st: 0,
        blk: 0,
        pf: 5,
        pts: 21,
      },
    ],
    teamTotals: {
      fg2: { made: 17, att: 37 },
      fg3: { made: 6, att: 8 },
      ft: { made: 11, att: 19 },
      reb: { off: 23, def: 34, tot: 57 },
      ast: 25,
      to: 22,
      st: 14,
      blk: 2,
      pf: 15,
      pts: 88,
    },
  },
  advanced: {
    pointsFromTurnovers: { home: 19, away: 22 },
    pointsInThePaint: { home: 36, away: 46 },
    secondChancePoints: { home: 17, away: 22 },
    fastBreakPoints: { home: 16, away: 29 },
    benchPoints: { home: 9, away: 18 },
    biggestLead: { home: 11, away: 21 },
  },
});
